- Account: 'BankA'
  Files:
    - 'data/public/transactions_bank_a.csv'
  Delimiter: ','
  Decimal: '.'
  DateKey: 'Date'
  DateFormat: '%Y-%m-%d'
  AmountKey: 'Amount'
  TextKeys:
    - 'Note'

- Account: 'BankB'
  Files:
    - 'data/public/transactions_bank_b*.csv'
  Delimiter: ';'
  Decimal: ','
  DateKey: 'Date'
  DateFormat: '%d.%m.%y'
  AmountKey: 'Value'
  TextKeys:
    - 'Notes'
