- Account: 'ACC-001'
  Files:
    - '../../data/public/bank_transactions_ACC-001.csv'
  Delimiter: ','
  Decimal: '.'
  DateKey: 'date'
  DateFormat: '%Y-%m-%d'
  AmountKey: 'amount'
  TextKeys:
    - 'description'
- Account: 'ACC-002'
  Files:
    - '../../data/public/bank_transactions_ACC-002.csv'
  Delimiter: ','
  Decimal: '.'
  DateKey: 'date'
  DateFormat: '%Y-%m-%d'
  AmountKey: 'amount'
  TextKeys:
    - 'description'
